openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: >
    API для керування контактами користувачів
tags:
  # теги, що ви будете використовувати
  - name: Contacts
    description: Operations about contacts
  - name: Auth
    description: Operations about auth
servers:
  - url: <http://localhost:3000>
  # - url: #посилання на задеплоєний сайт
paths:
  # тут будуть посилання на ендпоінти
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{contactId}/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
